---
title: "Bis15L Midterm 1"
author: "Kyra Kong"
date: '2023-01-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

select function helps with selecting columns of data

filter function helps with selecting rows of data

mutate function allows us to make new columns of data 

tabyl makes a table using the across more than one variable

hist makes a histogram

skim() can check to see if the output is as expected

summarize can help make a table or a complete set of data observations with specific functions
summarize_all() summarizes across all variables
 summarise(across(!c(species, island, sex, year), 
                   mean, na.rm=T))
                   
adding ! does the except or not these columns

%>%  is a pipe to help make data selection more easier

`n_distinct()` is a very handy way of cleanly presenting the number of distinct observations. Here we show the number of distinct genera over 100 in body weight.

 summary statistics, depending on your needs: sd(), min(), max(), median(), sum(), n() (returns the length of a column), first() (returns first value in a column), last() (returns last value in a column) and n_distinct() (number of distinct values in a column).

summarize(number_NAs=sum(is.na(body_mass_g))) <- can be used to determine how many NAs are present or
 any.na()

arrange can help put entries in ascending order to make it desc do arrange(desc(x))
 
count()` is an easy way of determining how many observations you have within a column. It acts like a combination of `group_by()` and `n()`.
 
fisheries<- fisheries %>% 
 mutate(across(c(country, isscaap_group_number, asfis_species_number, fao_major_fishing_area),as_factor)) as an easier way to mutate multiple columns of data as a factor

We will briefly introduce `if_else()` here because it allows us to use `mutate()` but not have the entire column affected in the same way. In a sense, this can function like find and replace in a spreadsheet program. With `ifelse()`, you first specify a logical statement, afterwards what needs to happen if the statement returns `TRUE`, and lastly what needs to happen if it's  `FALSE`.  

Have a look at the data from mammals below. Notice that the values for newborn include `-999.00`. This is sometimes used as a placeholder for NA (but, is a really bad idea). We can use `if_else()` to replace `-999.00` with `NA`. 
